"""empty message

Revision ID: 14805d3f3031
Revises: 43787b6fdcf4
Create Date: 2020-02-01 18:36:33.257029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14805d3f3031'
down_revision = '43787b6fdcf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'body',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=140),
               type_=sa.String(length=6000),
               existing_nullable=True)
    op.alter_column('task', 'complete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'complete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('article', 'body',
               existing_type=sa.String(length=6000),
               type_=mysql.VARCHAR(collation='utf8_bin', length=140),
               existing_nullable=True)
    # ### end Alembic commands ###
