"""empty message

Revision ID: 212a837f9725
Revises: 14805d3f3031
Create Date: 2020-02-01 18:37:47.938146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '212a837f9725'
down_revision = '14805d3f3031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'body',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=6000),
               type_=sa.String(length=10000),
               existing_nullable=True)
    op.alter_column('task', 'complete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'complete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('article', 'body',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(collation='utf8_bin', length=6000),
               existing_nullable=True)
    # ### end Alembic commands ###
