"""empty message

Revision ID: 87e7b76a088c
Revises: 834b1a697901
Create Date: 2020-01-30 16:03:16.394539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e7b76a088c'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messagetome',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('msg', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username', 'tel')
    )
    op.create_index(op.f('ix_messagetome_timestamp'), 'messagetome', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messagetome_timestamp'), table_name='messagetome')
    op.drop_table('messagetome')
    # ### end Alembic commands ###
